language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: svendeville_budget_management
    token:
      secure: MX8FmmF8MBuL8ayNXKvd8F/jDLgEBI4I0mg8jiUpBuqXpvx3YBBK6P4qSjrNja6qxtqdRkvNq+C3NNZ38Uxtrx27gbZPPqSt/UTVUblZOo95BuKrjP5ggaP7SoxSmGdvBTbK1DVHWCLIANY7t2w5pRp+EyxT15k24TSvIc7xPQfze/HE8VR4TYIRqYtXftKcoTesE0YaaVUnv2PCEqTisB/gcRJXc4ZUBs7INkc9TtdPyCicBbnZ84ul4IVRB02VFBt724PDlVDHE98ED5S83iobgMMHliQvOk4hkYi2wUPTR92OKCQHOUv0zTwz24BWxbOV8f5HctRBURczbNaZiGgYS8Cxl1ZfxkmlydXjmyribdIV3xqMJ40+LgCN3AYyShOVq1eYOCTZwyQCOvhoalkADp8VW1kZH6l1gE43FHiSoKHsoKZcDVNAVrLWvgWVWHPFz0IGVnHLST4wNFtlgXtfHZfIC9QWoe9JJ2+Er4J2OHngA+h3xA578TccVdlrBgAZRlEli2YvSLP6mAqkVfi/TQGOAukBDS9pzo7uEBrT2IW2wVo8qOQniidIPFyFpSBfzZleKujyLOvJk5tu0vd+Mj5G1BM8KNSexd45jEd/APPipB7TGLL3I7iyNy81bNYgJ05V56nG7KkqPd3kH2lAqtiyCHphnNbxcp1zVJg=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
