spring:
  jmx:
    enabled: false

info:
  app:
    name: ${spring.application.name}
    description : '@project.description@'
    version: '@project.version@'
    gitCommitId: '@git.commit.id@'

javafx:
  stage:
    resizable: true
    fullScreen: true
  title: Budget Managment